name: build_dagger

on:
  push:
    branches: ["main"]

jobs:
  dagger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Dagger build
        uses: dagger/dagger-for-github@v3
        with:
          version: latest
          cmds: version


